export const PLANS = [
  {
    id: 1,
    country: 'USA',
    name: 'Basic Plan',
    description: 'A basic internet plan for casual users.',
    durationMonth: 12,
    dataLimit: 500,
    speedLimitGb: 10,
    speedLimitMbps: 100,
    deviceLimit: 3,
    price: 29.99,
    config: '123123',
  },
  {
    id: 2,
    country: 'Canada',
    name: 'Standard Plan',
    description: 'A standard plan for families and small businesses.',
    durationMonth: 24,
    dataLimit: 1000,
    speedLimitGb: 20,
    speedLimitMbps: 200,
    deviceLimit: 5,
    price: 49.99,
    config: '123123',
  },
  {
    id: 3,
    country: 'UK',
    name: 'Premium Plan',
    description: 'A high-speed plan for heavy users and streaming.',
    durationMonth: 12,
    dataLimit: 2000,
    speedLimitGb: 50,
    speedLimitMbps: 500,
    deviceLimit: 10,
    price: 79.99,
    config: '123123',
  },
  {
    id: 4,
    country: 'Australia',
    name: 'Family Plan',
    description: 'An internet plan suitable for large households.',
    durationMonth: 18,
    dataLimit: 1500,
    speedLimitGb: 30,
    speedLimitMbps: 300,
    deviceLimit: 8,
    price: 59.99,
    config: '123123',
  },
  {
    id: 5,
    country: 'Germany',
    name: 'Business Plan',
    description: 'A premium plan for small to medium-sized businesses.',
    durationMonth: 36,
    dataLimit: 5000,
    speedLimitGb: 100,
    speedLimitMbps: 1000,
    deviceLimit: 20,
    price: 149.99,
    config: '123123',
  },
];
