name: Lint Fix

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Необходимо для пуша

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint Fix
        run: npm run eslint:fix

      - name: Run Stylelint Fix
        run: npm run stylelint:fix

      - name: Run Prettier Fix
        run: npm run prettier:fix
